
name: algo-trade-ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib
      - name: Run unit tests
        run: |
          python -m pytest -q
      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backtest-reports
          path: reports/**
