name: Revize v2.6 Hotfix Smoke

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install deps
        run: |
          pip install -e . || true
          pip install pandas numpy scikit-learn streamlit pydantic optuna pytest pyarrow
      - name: Run Golden & Smoke
        env:
          PYTHONPATH: .
        run: |
          pytest -q tests/golden/test_normalizer.py
          pytest -q tests/smoke/test_wf_engine.py
